spring:
  profiles:
    include: secret
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    #        H2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/db/order
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
logging.level:
  org:
    hibernate.SQL: debug